config/routes.rb
StaticSite::Application.routes.draw do

  root 'pages#home'

  get '/about' => 'pages#about', as: :about  #method can not have a dash, so we make an alias
  get '/privacy' => 'pages#privacy'

 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	#Anything we want
  end

  def about

  end

  def privacy

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StaticSite</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav>
	<%= link_to "Home", root_path %>
	<%= link_to "About Us", about_path %>
	<%= link_to "Privacy", privacy_path %>
	<!--<%= link_to "Home", '/' %>
	<%= link_to "Privacy", '/privacy' %> -->
</nav>
<!-- this generate the actual template page
THis page contains common code -->
<%= yield %>

<footer><%= Time.now.strftime("%A %m/%d/%Y") %></footer>
</body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p><%= "Number A: #{numA = 5**2}" %></p>
<p><%= "Number B: #{numB = numA-5}" %></p>
<p><%= "NUmber C: #{numC = numA%numB}" %></p>

app/views/pages/home.html.erb
<h1>Home</h1>
<p>Home Page</p>

app/views/pages/privacy.html.erb
<h1>Privacy</h1>

<%= "Hi there".upcase! %>

<% ["dog", "cat"].each do | animal | %>
<p><%= animal %></p>
<% end %>